### ISSUE TITLE
[Bug] Black Screen on Poco X6 Pro (with a workaround)

### ISSUE THREAD

**Issue by yxles-dev** [RPCS3-Android/rpcs3-android#91]
- **Describe the bug**
Running any game or the XMB on Alpha 1 or 2 build of the emulator shows a black screen when its compiling PPU Modules or somewhere in loading screen but I found out that running the emulator on a floating window makes it so that the whole loading screen is visible as well as the game. 

- **To Reproduce**
1. Open RPCS3
2. Make it into a floating window
3. Run any game that is supported
4. You will now see the whole loading screen without black screen
5. After loading screen it will also now show the game running

**Screenshots**
When running the emulator full screen:
![Image](https://github.com/user-attachments/assets/22a195d8-d662-4537-939f-5d182c30d40f)

When running the emulator on a floating window:
![Image](https://github.com/user-attachments/assets/fab6f6c6-3e7e-4c63-afd8-d505239e5072)
![Image](https://github.com/user-attachments/assets/328fbf6a-026e-4398-9a6a-766b7f3341c9)
![Image](https://github.com/user-attachments/assets/e98d1efc-29c3-4189-b39c-6e06c4edb5fc)

**Smartphone (please complete the following information):**
 - Device: Poco X6 Pro 5G
 - OS: HyperOS 2
 - Version: 2.0.102.0 Stable

**Additional context**
This bug report is just to report how the emulator works on this specific device and not a request for immediate support for it (just don't want to have any replies saying that I demand for it to be supported at such early state, I'm just reporting I swear 🤞)

**Comment by JLBB0807** [comment]
It's fixed in the new action build

**Comment by Meteb10** [comment]
I can confirm this happens on my Poco phone as well same OS and everything and no it's not fixed in the last action bulid

**Comment by JLBB0807** [comment]
Very curious, it must be a device specific problem as you are mentioning

**Comment by bartii76** [comment]
Happens on my Xiaomi 14T as well, it uses the same SoC as the X6 Pro

**Comment by ruban0** [comment]
It showing sometime sometimes just black screen we need to wait for fix

**Comment by yxles-dev** [comment]
> It's fixed in the new action build

> I can confirm this happens on my Poco phone as well same OS and everything and no it's not fixed in the last action bulid

Can confirm that the latest action build fixed the issue and made other games able to load on this device without crashing.

![Image](https://github.com/user-attachments/assets/86c3b247-7b71-4a30-97a9-8a6d113839df)
![Image](https://github.com/user-attachments/assets/0722fc44-4dbb-45d1-863e-e424a3d0b627)

**Comment by Meteb10** [comment]
> that

We must have a different issue then cause even on the newest action bulid I still can't launch a game unless on a floating window.

**Comment by yxles-dev** [comment]
> > that
> 
> We must have a different issue then cause even on the newest action bulid I still can't launch a game unless on a floating window.

Alpha 4 is now out, can you check and see if it works? I'll close this issue if it does

**Comment by bartii76** [comment]
Alpha 4 made my 14T unable to even launch anything, it just crashes while compiling PPU modules. I guess im just gonna wait for better mediatek support.
